'use strict';
const $=id=>document.getElementById(id), screen=$('screen'), hint=$('hint'), status=$('status');
const STORE='neural-journal-v1', LENGTH=8, enc=new TextEncoder(), dec=new TextDecoder();
let vault=null,key=null,entries=[],view='lock',sequence=[],first=null,busy=false,draft=null,saveQueue=Promise.resolve(),selectedDate=new Date(),datePart=0,page=0,filter='',failures=0;
const arrows={ArrowUp:'↑',ArrowDown:'↓',ArrowLeft:'←',ArrowRight:'→'};
const b64=a=>btoa(String.fromCharCode(...new Uint8Array(a)));
const un64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const dateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const displayDate=d=>new Date(d).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});
const say=s=>status.textContent=s;
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function button(label,action,small){const b=el('button',label);if(small)b.append(el('small',small));b.onclick=action;return b;}
function base(title,instruction){screen.replaceChildren();screen.className='';hint.textContent=instruction;if(title)screen.append(el('h1',title));}
function focusFirst(){screen.querySelector('textarea,input,button')?.focus();}
async function derive(seq,salt){const material=await crypto.subtle.importKey('raw',enc.encode(seq.join(',')),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:600000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
async function encrypt(data,k,salt){const iv=crypto.getRandomValues(new Uint8Array(12));return {version:1,salt,iv:b64(iv),cipher:b64(await crypto.subtle.encrypt({name:'AES-GCM',iv},k,enc.encode(JSON.stringify(data))))};}
function persist(){const snapshot=JSON.stringify(entries),k=key,salt=vault.salt;say('Saving…');saveQueue=saveQueue.catch(()=>{}).then(async()=>{const next=await encrypt(JSON.parse(snapshot),k,salt);localStorage.setItem(STORE,JSON.stringify(next));vault=next;say('Saved on this device');});saveQueue.catch(()=>say('Not saved. Keep this page open and try again.'));return saveQueue;}
function showLock(){view='lock';sequence=[];base(vault?'Journal locked':first?'Repeat your swipes':'Choose your swipe password','Swipe in any direction • 8 swipes');screen.className='lock';screen.append(el('p',vault?'Enter your eight-swipe sequence.':first?'Repeat the same eight swipes to confirm.':'Choose eight directions you can remember.','sub'),el('div','○'.repeat(LENGTH),'dots'));const row=el('div',undefined,'directions');Object.entries(arrows).forEach(([a,s])=>row.append(button(s,()=>swipe(a))));screen.append(row,button('Start over',()=>{first=null;showLock();}));if(!vault)screen.append(el('p','Your sequence encrypts your journal. Forgotten sequences cannot be recovered.','sub'));focusFirst();}
async function unlock(){busy=true;const seq=sequence.slice();say(vault?'Unlocking…':'Creating your journal…');try{if(vault){const k=await derive(seq,un64(vault.salt));let data;try{data=await crypto.subtle.decrypt({name:'AES-GCM',iv:un64(vault.iv)},k,un64(vault.cipher));}catch{failures++;say('Sequence not recognized. Try again.');showLock();return;}entries=JSON.parse(dec.decode(data));if(!Array.isArray(entries))throw Error('Invalid journal');key=k;}else{const salt=crypto.getRandomValues(new Uint8Array(16));const k=await derive(seq,salt);const next=await encrypt([],k,b64(salt));localStorage.setItem(STORE,JSON.stringify(next));vault=next;key=k;entries=[];}first=null;failures=0;say('Unlocked');newEntry();}catch{say('Cannot open the journal. Storage or encryption is unavailable.');showLock();}finally{busy=false;}}
function swipe(a){if(busy)return;if(view==='lock'){sequence.push(a);screen.querySelector('.dots').textContent='●'.repeat(sequence.length)+'○'.repeat(LENGTH-sequence.length);if(sequence.length===LENGTH){if(!vault&&!first){first=sequence.slice();showLock();say('Repeat to confirm');}else if(!vault&&sequence.join()!==first.join()){first=null;showLock();say('Sequences did not match. Choose again.');}else{if(failures>=5){busy=true;say('Please wait 15 seconds before trying again.');setTimeout(()=>{busy=false;showLock();say('Try your sequence again');},15000);}else unlock();}}return;}if(view==='write'&&a==='ArrowUp'){showMenu();return;}if(view==='read'){if(a==='ArrowDown'||a==='ArrowUp'){const t=screen.querySelector('.entry-text');t.scrollBy({top:a==='ArrowDown'?160:-160});return;}}if(view==='date'){const fields=[...screen.querySelectorAll('.search-fields button')];const part=fields.indexOf(document.activeElement);if(part>=0&&(a==='ArrowUp'||a==='ArrowDown')){datePart=part;changeDate(a==='ArrowUp'?1:-1);return;}}navigate(a);}
function navigate(a){const items=[...screen.querySelectorAll('button,input,textarea')];const at=items.indexOf(document.activeElement),delta=(a==='ArrowUp'||a==='ArrowLeft')?-1:1;items[(at+delta+items.length)%items.length]?.focus();}
function newEntry(){draft={id:crypto.randomUUID(),created:new Date().toISOString(),day:dateKey(new Date()),text:''};showWriter();}
function showWriter(){view='write';base('New entry','↑ Menu · Pinch the entry to handwrite');screen.append(el('p',displayDate(draft.created),'sub'));const t=el('textarea');t.placeholder='What’s on your mind?';t.setAttribute('aria-label','Journal entry. Pinch to handwrite or dictate.');t.value=draft.text;const update=()=>{if(draft.text===t.value)return;draft.text=t.value;draft.updated=new Date().toISOString();const i=entries.findIndex(e=>e.id===draft.id);if(i<0&&draft.text.trim())entries.unshift(draft);else if(i>=0)entries[i]=draft;persist();};t.addEventListener('input',update);t.addEventListener('change',update);screen.append(t,button('↑ Menu',showMenu));t.focus();}
function showMenu(){view='menu';base('Journal','Swipe to choose · Pinch to open');screen.append(button('Continue entry',showWriter),button('Previous entries',()=>{filter='';page=0;showHistory();},`${entries.filter(e=>e.text.trim()).length} saved entries`),button('Find a date',()=>{datePart=0;showDate();}),button('New entry',newEntry),button('Lock journal',lock));focusFirst();}
async function lock(){if(busy)return;busy=true;try{await saveQueue;key=null;entries=[];draft=null;first=null;showLock();say('Locked');}catch{say('Not saved. Journal remains open.');}finally{busy=false;}}
function showHistory(){view='history';base(filter?displayDate(filter+'T12:00:00'):'Previous entries','Swipe to choose · Pinch to read');const matches=entries.filter(e=>e.text.trim()&&(!filter||e.day===filter)).sort((a,b)=>b.created.localeCompare(a.created));const list=el('div',undefined,'list');matches.slice(page*3,page*3+3).forEach(e=>list.append(button(e.text.slice(0,60)+(e.text.length>60?'…':''),()=>showEntry(e),displayDate(e.created)+' · '+new Date(e.created).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'}))));if(!matches.length)list.append(el('p',filter?'No entries for this date.':'Your entries will appear here.','empty'));screen.append(list);const row=el('div',undefined,'row');if(page>0)row.append(button('Previous',()=>{page--;showHistory();}));if((page+1)*3<matches.length)row.append(button('More',()=>{page++;showHistory();}));screen.append(row,button('Back to menu',showMenu));focusFirst();}
function showEntry(e){view='read';base(displayDate(e.created),'↑ ↓ Scroll · Pinch to go back');screen.append(el('div',e.text,'entry-text'),button('Back to entries',showHistory));focusFirst();}
function changeDate(delta){const y=selectedDate.getFullYear(),m=selectedDate.getMonth(),d=selectedDate.getDate();if(datePart===2)selectedDate.setDate(d+delta);else{selectedDate.setDate(1);if(datePart===0)selectedDate.setFullYear(y+delta);else selectedDate.setMonth(m+delta);const last=new Date(selectedDate.getFullYear(),selectedDate.getMonth()+1,0).getDate();selectedDate.setDate(Math.min(d,last));}showDate();}
function showDate(){view='date';base('Find a date','← → Choose year / month / day · ↑ ↓ Change');const row=el('div',undefined,'search-fields');['Year','Month','Day'].forEach((label,i)=>{const values=[selectedDate.getFullYear(),selectedDate.toLocaleDateString(undefined,{month:'short'}),selectedDate.getDate()];const b=button(String(values[i]),()=>{datePart=i;changeDate(1);},label);if(i===datePart)b.className='selected';row.append(b);});screen.append(row);const controls=el('div',undefined,'row');controls.append(button('−',()=>changeDate(-1)),button('+',()=>changeDate(1)));screen.append(controls,button('Show entries',()=>{filter=dateKey(selectedDate);page=0;showHistory();}),button('Back to menu',showMenu));screen.querySelectorAll('.search-fields button')[datePart].focus();}
document.addEventListener('keydown',e=>{if(e.isComposing||e.repeat)return;if(arrows[e.key]){e.preventDefault();swipe(e.key);}else if(e.key==='Enter'&&!['TEXTAREA','INPUT'].includes(document.activeElement.tagName)){e.preventDefault();document.activeElement.click();}else if(e.key==='Escape'){e.preventDefault();if(key)showMenu();else showLock();}});
let pointer=null,suppressClick=false;
document.addEventListener('pointerdown',e=>{pointer={x:e.clientX,y:e.clientY,id:e.pointerId};});
document.addEventListener('pointerup',e=>{if(!pointer||e.pointerId!==pointer.id)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;pointer=null;if(Math.max(Math.abs(dx),Math.abs(dy))<45)return;suppressClick=true;setTimeout(()=>suppressClick=false,350);swipe(Math.abs(dx)>Math.abs(dy)?dx>0?'ArrowRight':'ArrowLeft':dy>0?'ArrowDown':'ArrowUp');});
document.addEventListener('pointercancel',()=>pointer=null);
document.addEventListener('click',e=>{if(suppressClick){e.preventDefault();e.stopImmediatePropagation();}},true);
window.addEventListener('pagehide',()=>{key=null;entries=[];draft=null;first=null;showLock();});
window.addEventListener('storage',e=>{if(e.key===STORE){location.reload();}});
$('date').textContent=new Date().toLocaleDateString(undefined,{month:'short',day:'numeric'});
try{const raw=localStorage.getItem(STORE);if(raw){vault=JSON.parse(raw);if(vault.version!==1||!vault.salt||!vault.iv||!vault.cipher)throw Error('Invalid vault');}if(!crypto.subtle)throw Error('Encryption unavailable');showLock();}catch{base('Journal unavailable','');screen.append(el('p','Encrypted storage could not be opened. Try a supported browser over HTTPS. Existing data has not been changed.'));}
